version: '2.1'
parameters:
  wf:
    type: string
    default: ""
jobs:
  wf1:
    docker:
      - image: cimg/base:2021.05
    steps:
      - run: echo "wf1"
  wf2:
    docker:
      - image: cimg/base:2021.05
    steps:
      - run: echo "wf2"
workflows:
  wf1:
    when:
      equal: [<< pipeline.parameters.wf >>, wf1]
    jobs:
      - wf1
  wf2:
    when:
      equal: [<< pipeline.parameters.wf >>, wf2]
    jobs:
      - wf2
