version: '2.1'
jobs:
  wf1:
    docker:
      - image: cimg/base:2021.05
    steps:
      - run: echo "wf1"
  wf2:
    docker:
      - image: cimg/base:2021.05
    steps:
      - run: echo "wf2"
workflows:
  wf1:
    jobs:
      - wf1
  wf2:
    jobs:
      - wf2
